export { Input, InputTextArea } from './Input.styles'
export { InputBigNumber } from './InputBigNumber'
export { InputPassword } from './InputPassword'
export { InputSearch } from './InputSearch'
export * from './Input.types'
